import type { Metadata } from "next";
import { Momo_Trust_Display, Roboto } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./_context/authentication";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import Provider from "./providers";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const momo_trust_display = Momo_Trust_Display({
  variable: "--font-momo",
  subsets: ["latin"],
  weight: ["400"],
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Jobhunt Kanban",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient()
  const { data: { user } } = await supabase.auth.getUser()

  return (
    <html
      lang="en"
      className={`${roboto.variable} ${momo_trust_display.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider user={user}>
          <Provider>
            {children}
          </Provider>
        </UserProvider>
      </body>
    </html>
  );
}